export enum EWorkOrderStatus {
  OPEN = 'OPEN',
  INSPECTING = 'INSPECTING',
  WAITING_QUOTATION = 'WAITING_QUOTATION',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REPAIRING = 'REPAIRING',
  QC = 'QC',
  READY_DELIVERY = 'READY_DELIVERY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  HOLD = 'HOLD',
}

export enum EFuelLevel {
  EMPTY = 'EMPTY',
  QUARTER = 'QUARTER',
  HALF = 'HALF',
  THREE_QUARTER = 'THREE_QUARTER',
  FULL = 'FULL',
}